# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alfaima L. Solano Blanco
email:
description: >- # this means to ignore newlines until "baseurl:"
  Instructor at Universidad de los Andes
  Operations research and analytics for decision making in sustainable supply chains
twitter_username: AlfaimaSB
github_username: AlfaimaSB
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alfaima L. Solano-Blanco"
  avatar : "/assets/images/profile-photo.png"
  bio    : "Instructor at Universidad de los Andes \n
  Operations research and analytics for decision making in sustainable supply chains"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alfaimasolano/"
    - label: "University page"
      icon: "fa fa-fw fa-university"
      url: "https://academia.uniandes.edu.co/AcademyCv/al.solano"
    - label: "Google Scholar"
      icon: "ai ai-fw ai-google-scholar"
      url: "https://scholar.google.com/citations?user=4iCKaIMAAAAJ&hl=en"
    - label: "ResearchGate"
      icon: "ai ai-fw ai-researchgate"
      url: "https://www.researchgate.net/profile/Alfaima-Solano-Blanco"
    - label: "OrcID"
      icon: "ai ai-fw ai-orcid"
      url: "https://orcid.org/0000-0001-9520-9541"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlfaimaSB"

#footer:
#  links:
#    - label: "LinkedIn"
#      icon: "fa fa-linkedin"
#      url: "https://www.linkedin.com/in/alfaimasolano/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"

atom_feed:
  hide: true

defaults:
   #_posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
